name: Build and push image

inputs:
  aws_account_id:
    description: 'AWS account id'
    required: true
  aws_region:
    description: 'AWS region'
    required: true
  aws_role:
    description: 'AWS role to assume'
    required: true
  api_key_ssm_param_name:
    description: ssm param to be consumed buy app
    required: true

runs:
  using: composite
  steps:
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          src:
            - 'src/**'

    - if: steps.changes.outputs.src == 'true'
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/${{ inputs.aws_role }}
        role-session-name: GitHubActions

    - if: steps.changes.outputs.src == 'true'
      name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - if: steps.changes.outputs.src == 'true'
      name: Setup aws ECR
      env:
        REPO_NAME: ${{ github.event.repository.name }}
        AWS_REGION: ${{ inputs.aws_region }}
      shell: bash
      run: |
        bash bin/create_ecr_repo.sh

    - if: steps.changes.outputs.src == 'true'
      name: Build
      env:
        LOCAL_IMAGE: ${{ github.event.repository.name }}:local
        ECR_BASE: ${{ inputs.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com
        ECR_URL: ${{ inputs.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ github.event.repository.name }}
        IMAGE_TAG: $(echo $GITHUB_SHA | cut -c 1-6)
        API_KEY_SSM_PARAM_NAME: ${{ inputs.api_key_ssm_param_name }}
      shell: bash
      run: |
        docker build --build-arg _next_public_woodland_creature=badger --build-arg _secret_woodland_creature=ferret --build-arg _api_key_ssm_param_name='${{ env.API_KEY_SSM_PARAM_NAME }}' --build-arg _aws_region='${{ env.aws_region }}' . -t ${{ env.LOCAL_IMAGE }}
        docker tag ${{ env.LOCAL_IMAGE }} ${{ env.ECR_URL }}:${{ env.IMAGE_TAG }}
        aws ecr get-login-password --region ${{ env.aws_region }} | docker login --username AWS --password-stdin ${{ env.ECR_BASE }}
        docker push ${{ env.ECR_URL }}:${{ env.IMAGE_TAG }}
